channels:
- conda-forge
dependencies:
- python=3.7.12
- pip
- pip:
  - numpy
  - pandas
  - mlflow
  - cloudpickle==2.2.1
  - nose==1.3.7
  - psutil==5.9.3
  - pytest==7.4.4
  - scikit-learn==0.21.3
name: mlflow-env
